### PR TITLE
🔧 Fix to template literals rendering null

### PR DESCRIPTION
**Pull request by rahulakrishna**
🔧 Inside `/server/services/ast/inspector.js`, create a new function
`getTemplateLiteralName`.
🔧 If the type is `TemplateLiteral` handle it using
`getTemplateLiteralName`, else fall back to the old `StringLiteral`
parsing logic

Resolves: #117

### CODE REVIEW

**Comment by rahulakrishna** [comment]
To be clear this renders `hello ${name}` not the variable value.

**Comment by rahulakrishna** [comment]
@Raathigesh, I'm not very good at naming things. Let me know if you need the function or variable names changed

**Comment by rahulakrishna** [comment]
@Raathigesh, can you look into this?

**Comment by Raathigesh** [comment]
Looks good to me. Thanks for getting this done and sorry for the late review.

**Pull request merged**
