### PR TITLE
This is it, test.todo() final PR

### PR DESCRIPTION
**Pull request by agustif**
Sorry for the previous mess, final PR with what was missing and nothing else, sorry but my IDE has lots of plugins which change stuff, Im gonna start use Atom or Notepad++ for PR's lol

### CODE REVIEW

**Comment by Raathigesh** [comment]
No worries. Thank you again :)

**Comment by agustif** [comment]
No problem, Thank you for being so open to contributors and helping me on the issue to tackle it by indicating me where I should start.

I love TypeScript because makes understanding new codebases much easier, it was a breeze to implement this and not even like 30 additions 10 deletions in 3-4 files, which took no more than 1-2 hours to ship, which is great!

Hope I can keep contributing, love the project and currently using it as my default jest runner.

I wonder if we could create a vscode-extension (It uses electron as Majestic, right?) so I can get rid of Test Explorer and just use majestic inside the editor? 🤔

**Comment by Raathigesh** [comment]
I'm glad you find the codebase easy to navigate. If you find other improvements, feel free to contribute. 

Majestic used to use electron but the latest version doesn't use electron. But majestic could be wrapper as an extension using the [web view API](https://code.visualstudio.com/api/extension-guides/webview).

**Comment by agustif** [comment]
> I'm glad you find the codebase easy to navigate. If you find other improvements, feel free to contribute.
> 
> Majestic used to use electron but the latest version doesn't use electron. But majestic could be wrapper as an extension using the [web view API](https://code.visualstudio.com/api/extension-guides/webview).

Wow, that sounds great, I'm gonna go ahead and open a separate issue on it to keep the conversation on topic!

**Pull request merged**
