### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by M4cs**
Add some more tags to my contributor depiction.

If you feel these are baseless feel free to deny.

### CODE REVIEW

**Comment by Raathigesh** [comment]
We use all contributors bot to add it instead of manually editing the file. You could just add a comment like [this](https://github.com/Raathigesh/majestic/pull/118#issuecomment-481533512) below so the bot will create a separate PR and then we can close this.

**Comment by M4cs** [comment]
@allcontributors[bot] please add @M4cs for code idea

**Comment by M4cs** [comment]
@allcontributors[bot] please add @M4cs for bug report

**Comment by Raathigesh** [comment]
@allcontributors[bot] please add @M4cs for idea bug report

**Pull request closed without merging**
